---
# tasks file for selinux (CentOS specific)

- name: (RedHat) install libselinux-python bindings ...
  yum: name=libselinux-python state=present
  tags: 
    - selinux

- name: (RedHat) set SELinux policy and state ...
  selinux: policy={{ selinux_policy }} state={{ selinux_state }}
  tags: 
    - selinux

