---
# tasks file for php-fpm
- name: "Load the OS specific variables"
  tags: 
    - php-fpm
  include_vars: "{{ ansible_os_family }}.yml"

- include: RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Copy default FPM configuration file
  template: dest={{ php_fpm_config_path }} src=php-fpm.conf.j2
  tags: php-fpm

- name: Copy the FPM configuration
  ini_file: >
    dest={{ php_fpm_config_path }}
    section="{{ item.section }}"
    option="{{ item.option }}"
    value="{{ item.value }}"
    backup=yes
  with_items: php_fpm_config
  register: copy_fpm_config

- name: Delete the include line from the ini file
  ini_file: >
    dest={{ php_fpm_config_path }}
    section=global
    option=include
    state=absent
    backup=no
  when: copy_fpm_config.changed

- name: Readd the include line to the ini file
  ini_file: >
    dest={{ php_fpm_config_path }}
    section=global
    option=include
    value="{{ php_fpm_pool_d }}/*.conf"
    state=present
    backup=no
  when: copy_fpm_config.changed

- name: Delete the default POOL configuration file
  file: >
    path={{ php_fpm_pool_d }}/{{ php_fpm_default_pool.name }}
    state=absent
  when: php_fpm_default_pool.delete

- name: Copy the POOL configurations
  template: >
    src=pool.conf.j2
    dest={{ php_fpm_pool_d }}/{{ item['name'] }}.conf
    backup=yes
  with_items: php_fpm_pools
  when: php_fpm_pools|lower != 'none'
  notify: restart php-fpm

- name: Start the php5-fpm service
  service: name={{ php_fpm_service_name }} state=started