--- 
# - hosts: all
#   become: true
#   become_method: sudo
#   roles: 
#     - python
#     - common
#     - SELinux
#     - ntp
#     - users

# - hosts: cfs_app
#   become: true
#   become_method: sudo
#   roles: 
#     - nfs-client
#     - memcached
#     - php
#     - composer
#     - wkhtmltopdf
#     - git

- include: webservers.yml
# - include: demons.yml
# - include: dbservers.yml
