--- 
- hosts: all
  become: true
  become_method: sudo
  roles: 
     - python
     - common
     - SELinux
     - ntp
    - users

 - hosts: cfs_app
   become: true
   become_method: sudo
   roles:
     - nfs-client
     - memcached
     - php
     - composer
     - wkhtmltopdf
     - git

 - hosts: webservers
   become: true
   become_method: sudo
   roles:
     - nginx
     - php-fpm
     - nodejs

 - hosts: demons
   become: true
   become_method: sudo
   roles:
     - cron

 - hosts: dbservers
   become: true
   become_method: sudo
   roles:
     - { role: mysql, when: "stage=='develop'" }