---

- name: Configuring cron tasks
  cron:
    cron_file: "{{ item.cron_file | default(omit) }}"
    day: "{{ item.day | default(omit) }}"
    hour: "{{ item.hour | default(omit) }}"
    job: "{{ item.job | default(omit) }}"
    minute: "{{ item.minute | default(omit) }}"
    month: "{{ item.month | default(omit) }}"
    name: "{{ item.name | default(item) }}"
    special_time: "{{ item.special_time | default(omit) }}"
    state: "{{ item.state | default(present) }}"
    user: "{{ item.user | default(cron_service_default_user) }}"
    weekday: "{{ item.weekday | default(omit) }}"
    disabled: "{{stage == 'develop' }}"
  with_items: cron_tasks