---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Download nodejs packages
  get_url: url='https://rpm.nodesource.com/setup' dest='/usr/src/setup-node' mode=0770

- name: Build nodejs
  command: 'bash /usr/src/setup-node'

- name: Install nodejs
  yum:  name=nodejs state=present
  when: ansible_os_family == 'RedHat'

- name: Install npm packages
  npm: name="{{item}}" global=yes state=present 
  with_items: nodejs_npm_modules