# list of cron entries (@see http://docs.ansible.com/cron_module.html)
# cron_tasks
#   - name: ...
#     cron_file: ...
#     day: ...
#     hour: ...
#     job: ...
#     minute: ...
#     month: ...
#     special_time: ...
#     state: ...
#     user: ...
#     weekday: ...
#
cron_service_default_user: www-data
cron_tasks:
      - name: Run EscaneadorXMLBatch
        minute: '*/1'
        job: 'php /home/confirmsign.com/public_html/_script/cron/lanzador_procesos.php "EscaneadorXMLBatch" --nombre_proceso="Cron_EscaneadorXML"'