---
enable_nginx: true
php_fpm_listen:  9000

php_fpm_pools:
 - name: fenec
   user: www-data
   group: www-data
   listen: '127.0.0.1:{{php_fpm_listen}}'
   chdir: /

php_fpm_pool_defaults:
  # Ondemand for low-traffic sites, dynamic for high-traffic on shared pools, and static when box dedicated to single site
  pm: dynamic
  # Used by ondemand, dynamic and static
  pm.max_children: "{{ ansible_processor_vcpus * 2 }}"
  # Used only when pm_type = dynamic
  # These are absurdly low, just as safe defaults
  # Make sure to also increase pm_max_children  
  # Default Value: min_spare_servers + (max_spare_servers - min_spare_servers) / 2
  pm.start_servers: 2
  pm.min_spare_servers: 1
  pm.max_spare_servers: 3
  pm.status_path: /status
  # Restart php worker after this many requests to prevent memory leaks from blowing up  
  pm.max_requests: 10000

php_fpm_default_pool:
  delete: yes
  name: www.conf

php_fpm_ini:
 - option: "engine"
   section: "PHP"
   value: "1"
 - option: "error_reporting"
   section: "PHP"
   value: "E_ALL & ~E_DEPRECATED & ~E_STRICT"

php_fpm_config:
 - option: "error_log"
   section: "global"
   value: "/var/log/php5-fpm.log"


# Extra params for server proxy
php_fpm_extra_fastcgi_params: ''

#php custom config vars 

php_memory_limit: "128M"

php_max_input_vars: "1000"