---
# tasks file for mysql

- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install the mysql packages 
  yum: name={{ item }} state=installed
  with_items: 
    - mysql-server
    - mysql
    - MySQL-python
  when: ansible_os_family == 'RedHat'

- name: Check mysql state started  
  service: name={{ mysql_service }} state=started

- name: create datadir if different to default
  file: path={{ mysql_data_dir }} state=directory owner=mysql group=mysql
  when: mysql_data_dir != '/var/lib/mysql'

- name: copy the my.cnf file
  template: src=my.cnf.{{ ansible_os_family }}.j2 dest={{ mysql_conf_dir }}/my.cnf
  notify: restart mysql

- name: update mysql root password for all root accounts
  mysql_user: name=root host={{ item }} password={{ mysql_root_db_pass }}
  with_items:
   - "{{ ansible_hostname|lower() }}"
   - 127.0.0.1
   - ::1
   - "localhost"
  when: mysql_root_db_pass != ''

- name: copy .my.cnf file with root password credentials
  template: src=.my.cnf.j2 dest=/root/.my.cnf mode=0600

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
   - localhost
   - "{{ ansible_hostname|lower() }}"

- name: remove the test database
  mysql_db: name=test state=absent

- name: create the databases
  mysql_db: name={{ item.name }} state=present
  with_items: mysql_db
  when: mysql_db|lower() != 'none'

- name: create the database users
  mysql_user: name={{ item.name |default("myconfirms") }} password={{ item.pass|default("Impresionant3") }} priv={{ item.priv|default("*.*:ALL") }} state=present host={{ item.host | default("localhost") }}
  with_items: mysql_users
  when: mysql_users|lower() != 'none'

- name: Copy file schema for databases
  copy: src='{{item.name}}.schema.sql' dest=/tmp
  with_items: mysql_db

- name: Import schema for databases
  mysql_db: name='{{item.name}}' state=import target='/tmp/{{item.name}}.schema.sql'
  with_items: mysql_db