---
# tasks file for git
- name: Install git packages
  yum: name={{ item }} state=present
  with_items: git_packages
  tags: git

- name: Configure git for all users
  template: src=gitconfig.j2 dest='/home/{{item.username}}/.gitconfig'
  with_items: users
