stage: 'production'

nfs_directories: 
  - { src: '192.168.11.6:/var/nfs/confirmsign.com/_log',        name: '/media/confirmsign.com/_log',     fstype: 'nfs4', opts: 'intr,hard' }
  - { src: '192.168.11.6:/var/nfs/confirmsign.com/_file',       name: '/media/confirmsign.com/_file',    fstype: 'nfs4', opts: 'intr,hard' }
  - { src: '192.168.11.6:/var/nfs/confirmsign.com/_themes',     name: '/media/confirmsign.com/_themes',  fstype: 'nfs4', opts: 'intr,hard' }
  - { src: '192.168.11.6:/var/nfs//confirmsign.com/_filetmp',   name: '/media/confirmsign.com/_filetmp', fstype: 'nfs4', opts: 'intr,hard' }
  - { src: '192.168.11.6:/var/nfs/confirmsign.com/_filetmp',    name: '/media/confirmsign.com/_ftp',     fstype: 'nfs4', opts: 'intr,hard' }
  - { src: '192.168.11.6:/var/nfs/AS2',                         name: '/media/AS2',                      fstype: 'nfs4', opts: 'intr,hard' }
  - { src: '192.168.11.6:/var/nfs/iadi',                        name: '/media/iadi',                     fstype: 'nfs4', opts: 'intr,hard' }
  - { src: '192.168.11.6:/var/nfs/iado',                        name: '/media/iadi',                     fstype: 'nfs4', opts: 'intr,hard' }