nfs_directories_extra:
  - { src: '192.168.11.6:/var/nfs/confirmsign.com/_log',     name: '/mnt/confirmsign.com/_log',     fstype: 'nfs4', opts: 'intr,hard' }
  - { src: '192.168.11.6:/var/nfs/confirmsign.com/_file',    name: '/mnt/confirmsign.com/_file',    fstype: 'nfs4', opts: 'intr,hard' }
  - { src: '192.168.11.6:/var/nfs/confirmsign.com/_themes',  name: '/mnt/confirmsign.com/_themes',  fstype: 'nfs4', opts: 'intr,hard' }
  - { src: '192.168.11.6:/var/nfs/confirmsign.com/_filetmp', name: '/mnt/confirmsign.com/_filetmp', fstype: 'nfs4', opts: 'intr,hard' }


# list of cron entries (@see http://docs.ansible.com/cron_module.html)
# cron_tasks
#   - name: ...
#     cron_file: ...
#     day: ...
#     hour: ...
#     job: ...
#     minute: ...
#     month: ...
#     special_time: ...
#     state: ...
#     user: ...
#     weekday: ...
#
cron_service_default_user: www-data
cron_tasks:
      - name: Run EscaneadorXMLBatch
        minute: '*/1'
        job: 'php /home/confirmsign.com/public_html/_script/cron/lanzador_procesos.php "EscaneadorXMLBatch" --nombre_proceso="Cron_EscaneadorXML"'