---
# tasks file for common
- name:  (System) create admin group
  group: name=admins state=present

- name:  (System) create develop group.
  group: name=develops state=present

- name:  (System) create deployer group.
  group: name=deployers state=present

- name: (System) create admin user.
  user: name=cfs comment="Default administrator user"  uid=2001 group=admins

- name: (System) create deployer user.
  user: name=devops comment="Default develop user"  uid=2002 group=develops

- name: (System) create deployer user.
  user: name=deployer comment="Default deployer user"  uid=2003 group=deployers

- name: (RedHat) upgrade all packages.
  yum:  name=* state=latest
  when: ansible_os_family == 'RedHat'

- name: (RedHat) upgrade all packages.
  yum:  name=nano state=present
  when: ansible_os_family == 'RedHat'