---
# tasks file for php
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - php

- include: RedHat.yml
  when: "ansible_os_family == 'RedHat'"
  tags:
    - php   